import React from "react";
import "@/styles/global.css";
import theme from "@/styles/theme";
import type { Metadata } from "next";
import { Footer } from "@/components/footer/Footer";
import { ThemeProvider } from "@mui/material/styles";
import { NavigationBar } from "@/components/navigation-bar/NavigationBar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <NavigationBar />
            {children}
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
